ThrashingCode/FacePalm

README.md
Merge this to receive a badge indicating the number of issues in the ready column on your waffle.io board at https://waffle.io/ThrashingCode/FacePalm
This was requested by a real person (user lelamson) on waffle.io, we're not trying to spam you.
=> Waffles Badge

lunchspot.css, lunchspot.html, lunchspot.js
@naveed13 initial commit for search results page
=> initial commit result page

form.html
@naveed13 please merge this with the master branch.
=> initial html layout for form.html

index.html
@nick-peters Please merge to master - added index.html (frontpage);
=> added frontpage index.html

form.css, form.html
I added a CSS file for the form and added grids. 
@lelamson will you please take a look and merge the changes. Thanks.
=> additional changes to form layout w grids

lunchspot.html, lunchspot.js
@matt-ralston Please check & merge
=> add PrintLoc

index.html, index.js
@lelamson please check and merge to master.
=> added index.html and index.js (frontpage)

form.js, index.js, main.js
@lelamson Merge this please, thanks!
=> Modified JS files to begin integration

main.js
=> <body> tag id handling

form.html, main.js
@lelamson please merge with master.
=> synching up js files

lunchspot.html
@nick-peters Please review and merge please.
=> add js reference to main.js

index.css, index.html, index.js
=> add index.html and index.css for frontpage

index.html, main.js
@nick-peters please check and merge
=> changes to main.JS and index.html

main.js
@nick-peters please check and merge
=> added cuisineCalc function

form.css, form.html, main.js
@nick hey this is ready for you.
=> fixed merge conflict on local machine

main.js
=> working on disabling submit button

form.html, main.js
=> add user selected cuisine loc cost to storage

form.html, main.js
@nick-peters Wired up the submit button
=> add API search functionality to submit buttom

aboutUs.html, index.css, main.js
=> index aboutUs and js

main.js
@nick-peters replaced main.js as requested
=> restore main.js

lunchspot.html, lunchspot.js, main.js
@nick-peters add functionality so API result display to results page
=> add API search result to final page

aboutUs.html, index.css, index.html
@nick-peters please check and merge
=> index.html  index.css AboutUs.html

form.css, form.html
@nick-peters can you please merge this. There shouldn't be many conflicts, it is just a few styling changes to the form page.
=> a few styling changes to form.html form.css

aboutUs.html, index.css
@matt-ralston please check and merge ...
=> index.css & AboutUs.html

index.css, index.html
@matt-ralston please check and merge
=> index.css & AboutUs.html and index.html

lunchspot.js
@matt-ralston fixed map bug to center correctly on marker
=> fix results page map load bug
